### ISSUE TITLE
Would you like an English translation?

### ISSUE THREAD

**Issue by ScottChesworth** [GerardKessler/whatsapp#2]
Hey Gerardo,

Would you like an English translation for this add-on? I don't have a GitHub environment set up here at the moment, but I can do it if you send me the po file. I can also translate the ReadMe.

**Comment by ghost** [comment]
Hi Scott. Thank you very much for the offer.I attach the files.  De: ScottChesworthEnviado: martes, 26 de julio de 2022 09:06 a. m.Para: GerardKessler/whatsappCC: SubscribedAsunto: [GerardKessler/whatsapp] Would you like an English translation? (Issue #2) Hey Gerardo,Would you like an English translation for this add-on? I don't have a GitHub environment set up here at the moment, but I can do it if you send me the po file. I can also translate the ReadMe.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 
[WS-translate-en.zip](https://github.com/GerardKessler/whatsapp/files/9190263/WS-translate-en.zip)

**Comment by ScottChesworth** [comment]
Here you go dude. If there are any problems, just shout.
[WS-translate-en completed.zip](https://github.com/GerardKessler/whatsapp/files/9224121/WS-translate-en.completed.zip)

**Comment by ghost** [comment]
Perfect. I have included the translation in version 1.3 of the addon. regards
